### ISSUE TITLE
alphabet doesn't filter in chrome

### ISSUE THREAD

**Issue by clechner77** [esteinborn/jquery-listnav#34]
Clicking on a letter doesn't filter in Chrome.  No error in console.  Works on all other browsers.

**Comment by esteinborn** [comment]
Please provide a URL where you are seeing this and I'll see if I can figure out a fix for you.






On Wed, Aug 26, 2015 at 6:07 PM -0700, "clechner77" <notifications@github.com> wrote:












Title says it all.  Clicking on a letter doesn't filter in Chrome.  No error in console.  Works on all other browsers.

**Comment by clechner77** [comment]
Here's what doesn't make sense.  I had 3 people test your demo on chrome and it didn't work for anyone.  I assumed it didn't work anywhere on Chrome.  I logged into 2 virtual machines with the same version of chrome and the demo worked.  Also tried out browserstack.com and the demo worked as well.  That said, my local version of chrome with all extensions disabled still doesn't work.  I'm not sure what the issue is here.  I use chrome as my main test browser for development so if there were JS issues I would think something would have popped up.
It's a head scratcher why it works on some machine and not others and all the same version of chrome too.  Not sure what else to look at.  Any ideas?

Date: Wed, 26 Aug 2015 18:14:53 -0700

**Comment by clechner77** [comment]
Here's the issue.  Chrome and touch events.  If chrome has touch events enabled (or if it's on automatic and the client has a touch enabled machine) and has a trackpad or mouse, the alphabet will not filter on click.  Touch will work just fine, but a mouse click will not filter.

If you disable touch events within chrome -- chrome://flags, Enable Touch Events: disabled -- then the mouse/trackpad will work.  I verified this on several machines with both your test/demo pages and a quick sample I put together.

I thought I was losing my mind for a while there.

**Comment by esteinborn** [comment]
Nice research! Thanks!
So the issue stems from the check in the JS for touch events existing. When they exist, they use touch events. 
So the fix is to check for the existence of both and then fire the filter change on them.
I should have a fix by tomorrow.





On Thu, Aug 27, 2015 at 9:20 AM -0700, "clechner77" <notifications@github.com> wrote:












Here's the issue.  Chrome and touch events.  If chrome has touch events enabled (or if it's on automatic and the client has a touch enabled machine) and has a trackpad or mouse, the alphabet will not filter on click.  Touch will work just fine, but a mouse click will not filter.



If you disable touch events within chrome -- chrome://flags, Enable Touch Events: disabled -- then the mouse/trackpad will work.  I verified this on several machines with both your test/demo pages and a quick sample I put together.



I thought I was losing my mind for a while there.

**Comment by clechner77** [comment]
You could remove the clickEventType operator and make it a normal click event.  Then, extend the click event with --
```javascript
$.fn.click = function(listener) {
    return this.each(function() {
       var $this = $( this );
       $this.on(‘vclick’, listener);
    });
};
```

**Comment by esteinborn** [comment]
Thanks for diagnosing this issue for me. I've fixed it in the latest push. and made a meme for you:

![063c4ac4-8244-4d0e-b09a-1defa3956a06](https://cloud.githubusercontent.com/assets/308007/9638273/d516ae6e-5173-11e5-9a7f-c77744df028b.jpg)
